# Generated by Django 5.1 on 2024-08-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличными"), ("ONLINE", "Онлайн")],
                max_length=35,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
