# Generated by Django 5.1 on 2024-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличными"), ("ONLINE", "Онлайн")],
                default="ONLINE",
                max_length=35,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
