# Generated by Django 5.1 on 2024-08-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="sessions_id",
            new_name="session_id",
        ),
    ]
